### ISSUE TITLE
Error: Couldn't register hotkey, closing application.

### ISSUE THREAD

**Issue by HellfireXD** [TorinFelton/SpotlightX#11]
After installing, the app worked fine for the first try, after that I started getting an error stating "Couldn't register hotkey, closing application".  
I did an uninstall and reinstall just to make sure but ran into the same error.

![image](https://user-images.githubusercontent.com/7536673/83963561-0662ce00-a875-11ea-8381-f0dde0eb856f.png)

**Comment by HellfireXD** [comment]
Update: If i kill the "CleanUI.exe" app via Task manager then I can launch it again.

**Comment by HellfireXD** [comment]
I put together a small .cmd file to kill the process and reopen it and it seams to work.  Best I can tell is that clicking the icon tries to start a new instance of the app instead of calling up the original. 

`@Echo off`
`color 08`
`cls`
`taskkill /IM CleanUI.exe > Nul`
`taskkill /IM CleanUI.exe > Nul`
`taskkill /IM CleanUI.exe > Nul`
`taskkill /IM CleanUI.exe > Nul`
`cls`
`PowerShell.exe -command "start-sleep -Seconds 1" > Nul`
`Start "SpotLightX" CleanUI.exe`
`exit`

**Comment by TorinFelton** [comment]
Hey, so I probably should've explaiend this better - when  you start the app once, it will continue running in the background and the bar will just pop up whenever you press Alt + S, so there is no need to run the shortcut again as SpotlightX never closes the application (unless you type "exit"). As well as this, it is automatically moved to the startup folder on install, so whenever you startup your pc there is no need to run it as it'll already be there in the background and you can just bring it up using Alt + S.
I will likely change the error message to be more descriptive at some point though, as it seems a few people have this problem.
