### ISSUE TITLE
The coloring of the GUI could be switched

### ISSUE THREAD

**Issue by SamsiFPV** [TorinFelton/SpotlightX#4]
I like the smooth transition of the blue in the GUI, but how about putting the light blue part on the right, to increase contrast for better readability? Also a option  to increase font size would be nice.

**Comment by SamsiFPV** [comment]
![image](https://user-images.githubusercontent.com/46871811/83738580-c58c6e80-a654-11ea-9002-65ab068c6899.png)
Here is it. And tbh, it looks horrible. But i still think an option for setting colors should be made sometime. Maybe some color presets.

**Comment by TorinFelton** [comment]
Will likely just make some commands to allow the user to change font / gradient / offset, etc. Then post some example settings for presets. Will work on this after a bit of organisation
