### ISSUE TITLE
Opening any app which is not in the programs folder

### ISSUE THREAD

**Issue by SamsiFPV** [TorinFelton/SpotlightX#5]
The Search bar currently isn't able to open Windows Store Apps like Netflix or Spotify. Also it pretty much doesn't open any App whcih isn't in the Programs folder. Which makes sense for searching time, but at least searching the Desktop would be nice.

**Comment by TorinFelton** [comment]
Hey! Worked on it for an hour or two and it's finished. You can now use the `addpath` and `removepath` commands to add all the files in the specified folder path. This will restart SpotlightX and then mean you can autocomplete and run any of the files in that folder too.

**Comment by TorinFelton** [comment]
This will work only for any **files** in the specified paths, and cannot yet open folders - though I'll be working on that. If you do open a file, whatever it is, it'll run with the default opening program set for that file (so a .docx will open in Word, etc.)
